### ISSUE TITLE
Failing to get back to "waiting for ads" state after blocking an ad

### ISSUE THREAD

**Issue by sappelhoff** [vsvinav/spotify-adblock-linux#10]
Hi, thanks for this great package :-)

I was testing it today and it definitely shut down spotify at advertisement onset, and then immediately restarted spotify. 

However, right afterwards it seems to be running into the following error:

![image](https://user-images.githubusercontent.com/9084751/74647292-b522b780-517b-11ea-8e0b-182aa30f9d43.png)

Do you have any advise on how to fix this?

My current fix is to interrupt adspotter and then restart it.

**Comment by sappelhoff** [comment]
actually, this error does not break adspotter ... it simply disturbes the output of the program, see:

![image](https://user-images.githubusercontent.com/9084751/74943533-d215ef80-53f4-11ea-9580-8911a348d655.png)

**Comment by vsvinav** [comment]
But do these logs stop the program from working? The ads are still not coming, right?

**Comment by bbhtt** [comment]
![Screenshot_2020-04-20_09-20-57](https://user-images.githubusercontent.com/62639087/79719064-4ab50180-82fb-11ea-8b89-19c059417be5.png)

Are you missing packages, because I don't have that error?

**Comment by sappelhoff** [comment]
> The ads are still not coming, right?

yes, it still works fine

> Are you missing packages, because I don't have that error?

probably, yes



I started to use `nohup python adspotter &` and then close the terminal I started the process from ... so this issue doesn't bother me anymore.

And it was not an issue of the code in this repo anyways :-)

So closing.
