### ISSUE TITLE
adspotter using high amount of CPU

### ISSUE THREAD

**Issue by sappelhoff** [vsvinav/spotify-adblock-linux#11]
When running adspotter I have noticed my laptop's fan starting to get very busy. After some investigation using `htop`, I found that the program is using between 35 and 40% of the CPU.

Is that to be expected?

![image](https://user-images.githubusercontent.com/9084751/74650370-d9819280-5181-11ea-9e64-acacb3332f5e.png)

For now, I fixed it by inserting an additional `time.sleep(1)` within the while loop checking for ads. This does not seem to impair ad detection, yet it significantly reduces the CPU load.

**Comment by vsvinav** [comment]
Yeah, that should probably do it, you can send a pull request if it's working for you. I actually don't have time to test or work on it right now. Also, close this issue if you think it's resolved.

**Comment by sappelhoff** [comment]
okay @vsvinav see #15 it's been working well for these past weeks.
