### ISSUE TITLE
Unicode Encode Error on Line 58

### ISSUE THREAD

**Issue by bbhtt** [vsvinav/spotify-adblock-linux#12]
Hi I got the following issue:

   _        _   ___                _     _
  /_\    __| | / __|  _ __   ___  | |_  | |_   ___   _ _
 / _ \  / _` | \__ \ | '_ \ / _ \ |  _| |  _| / -_) | '_|
/_/ \_\ \__,_| |___/ | .__/ \___/  \__|  \__| \___| |_|
                     |_|v0.0.1
`
[STATUS]: waiting for ads...
Traceback (most recent call last):
  File "adspotter", line 74, in <module>
    main()
  File "adspotter", line 58, in main
    title = str(dict(player.Metadata).get(dbus.String('xesam:title')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 10: ordinal not in range(128)
`

**Comment by sappelhoff** [comment]
are you running adspotter with Python 3?

**Comment by bbhtt** [comment]
Yeah, I tried to run it with python3 but somehow Ubuntu's default is python2 and pip3 package did not install.So it was runnimg with python2. I had to remove pip3 via apt and reinstall it again to make it work. The error is now gone.

**Comment by sappelhoff** [comment]
Cool, don't forget to close the issue ;-)
