### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by lwbaqueros** [vsvinav/spotify-adblock-linux#13]
(spotify:102441): GdkPixbuf-WARNING **: 00:15:10.379: Cannot open pixbuf loader module file '/home/lwbaqueros/snap/spotify/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/lwbaqueros/snap/spotify/common/.cache/gdk-pixbuf-loaders.cache
to make things work again for the time being.

**Comment by lwbaqueros** [comment]
(spotify:97074): GdkPixbuf-WARNING **: 00:10:54.569: Cannot open pixbuf loader module file '/home/lwbaqueros/snap/spotify/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/lwbaqueros/snap/spotify/common/.cache/gdk-pixbuf-loaders.cache
to make things work again for the time being.
[STATUS]: Detected Ad
[STATUS]: Blocking Ad
Gtk-Message: 00:15:08.855: Failed to load module "gail"
Gtk-Message: 00:15:08.855: Failed to load module "atk-bridge"
Gtk-Message: 00:15:08.874: Failed to load module "canberra-gtk-module"

**Comment by sappelhoff** [comment]
What is your error actually? Is adspotter working, or not?

The 

```
[STATUS]: Detected Ad
[STATUS]: Blocking Ad
Gtk-Message: 00:15:08.855: Failed to load module "gail"
Gtk-Message: 00:15:08.855: Failed to load module "atk-bridge"
Gtk-Message: 00:15:08.874: Failed to load module "canberra-gtk-module"
```

part looks a lot like what I reported in https://github.com/vsvinav/spotify-adblock-linux/issues/10

**Comment by lwbaqueros** [comment]
I had one dependency not loaded, but finally, It works.

The program closes Spotify when it detects an advertisement and reopens
Spotify to continue playing the next song.

**Comment by sappelhoff** [comment]
which dependency was that?

**Comment by lwbaqueros** [comment]
I had installed *firejail, and apparmor-profiles,* It blocks your script
somehow. When I delete it and reinstall apparmor again I lost some package
(I did not remember what), then I just made ´$ sudo apt update ´ ´$ sudo
apt update ´ ´$ sudo apt upgrade´ and then your script works again.

**Comment by sappelhoff** [comment]
okay :-) don't forget to close the issue, please 

> your script works again.

it's actually @vsvinav's script, but he doesn't have time currently.
