### ISSUE TITLE
AdSpotter will only work when started after an ad has started playing

### ISSUE THREAD

**Issue by 4589367** [vsvinav/spotify-adblock-linux#6]
Starting Spotify, then starting AdSpotter will keep it in "Waiting for ads" mode until I relaunch when an ad is playing. 

Debian 8 
Spotify version 1.0.77.338.g758ebd78, Copyright (c) 2018, Spotify Ltd

**Comment by vsvinav** [comment]
> Starting Spotify, then starting AdSpotter will keep it in "Waiting for ads" mode until I relaunch when an ad is playing.
> 
> Debian 8
> Spotify version 1.0.77.338.g758ebd78, Copyright (c) 2018, Spotify Ltd

Thanks for reporting this issue, please check now and let me know if it works fine now.
