### ISSUE TITLE
Exception in dbus

### ISSUE THREAD

**Issue by carg0cult** [vsvinav/spotify-adblock-linux#9]
Always get an exception after like 10 seconds after starting adspotter

   _        _   ___                _     _
  /_\    __| | / __|  _ __   ___  | |_  | |_   ___   _ _
 / _ \  / _` | \__ \ | '_ \ / _ \ |  _| |  _| / -_) | '_|
/_/ \_\ \__,_| |___/ | .__/ \___/  \__|  \__| \___| |_|
                     |_|v0.0.1

[STATUS]: waiting for ads...
Traceback (most recent call last):
  File "adspotter", line 74, in <module>
    main()
  File "adspotter", line 58, in main
    title = str(dict(player.Metadata).get(dbus.String('xesam:title')))
  File "/home/rob/.local/lib/python3.7/site-packages/mpris2/decorator/attribute.py", line 33, in __get__
    result = props.Get(iface, self.attr.__name__)
  File "/home/rob/.local/lib/python3.7/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/home/rob/.local/lib/python3.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/home/rob/.local/lib/python3.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

**Comment by carg0cult** [comment]
Spotify is running. It makes no difference whether an ad or music is playing

**Comment by vsvinav** [comment]
> Always get an exception after like 10 seconds after starting adspotter
> 
> /_\ __| | / __| _ __ ___ | |_ | |_ ___ _ _ / _ \ / _` | __ \ | '_ \ / _ \ | _| | _| / -_) | '_| /_/ _\ __,_| |_**/ | .**/ ___/ __| __| ___| |_| |_|v0.0.1
> 
> [STATUS]: waiting for ads...
> Traceback (most recent call last):
> File "adspotter", line 74, in
> main()
> File "adspotter", line 58, in main
> title = str(dict(player.Metadata).get(dbus.String('xesam:title')))
> File "/home/rob/.local/lib/python3.7/site-packages/mpris2/decorator/attribute.py", line 33, in **get**
> result = props.Get(iface, self.attr.**name**)
> File "/home/rob/.local/lib/python3.7/site-packages/dbus/proxies.py", line 70, in **call**
> return self._proxy_method(*args, **keywords)
> File "/home/rob/.local/lib/python3.7/site-packages/dbus/proxies.py", line 145, in **call**
> **keywords)
> File "/home/rob/.local/lib/python3.7/site-packages/dbus/connection.py", line 651, in call_blocking
> message, timeout)
> dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

Which distro of linux are you using?

**Comment by carg0cult** [comment]
Ubuntu 19.10

**Comment by vsvinav** [comment]
> Ubuntu 19.10

When you run the Spotify app for Linux, do you get a sticky notification if the song is playing? I'm talking about the area right next to where you get the entire calendar. And if it is there, can you control the player with options like next, previous song; play/pause?

**Comment by carg0cult** [comment]
I do get a notification right under the calendar. But it's not sticky. It vanishes after a few seconds.
I'm not sure what you mean by control the player. I have no controls other than in the Spotify app.

**Comment by vsvinav** [comment]
> I do get a notification right under the calendar. But it's not sticky. It vanishes after a few seconds.
> I'm not sure what you mean by control the player. I have no controls other than in the Spotify app.

Alright, from what I understand you're using the Spotify app for linux and not having a constant sticky notification, the dbus media player notification, which looks like:
![Screenshot from 2020-01-16 14-25-06](https://user-images.githubusercontent.com/42143636/72508656-151bfa80-386c-11ea-9b2a-daa7d5e07e10.png)

The entire script is based on the dbus, the script does not blacklist any API and hence you're getting the issue. Maybe you should look into why you aren't getting the dbus notification for Spotify.

**Comment by carg0cult** [comment]
Thanks. Found the notification and controls now thanks to your screenshot. They were hanging. It's working after a reboot. So it's not an issue of adspotter. Thank you very much.
